// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: server.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MediaTextServiceClient is the client API for MediaTextService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MediaTextServiceClient interface {
	Find(ctx context.Context, in *FindMediaTextRequest, opts ...grpc.CallOption) (*FindMediaTextReply, error)
}

type mediaTextServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaTextServiceClient(cc grpc.ClientConnInterface) MediaTextServiceClient {
	return &mediaTextServiceClient{cc}
}

func (c *mediaTextServiceClient) Find(ctx context.Context, in *FindMediaTextRequest, opts ...grpc.CallOption) (*FindMediaTextReply, error) {
	out := new(FindMediaTextReply)
	err := c.cc.Invoke(ctx, "/MediaTextService/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediaTextServiceServer is the server API for MediaTextService service.
// All implementations must embed UnimplementedMediaTextServiceServer
// for forward compatibility
type MediaTextServiceServer interface {
	Find(context.Context, *FindMediaTextRequest) (*FindMediaTextReply, error)
	mustEmbedUnimplementedMediaTextServiceServer()
}

// UnimplementedMediaTextServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMediaTextServiceServer struct {
}

func (UnimplementedMediaTextServiceServer) Find(context.Context, *FindMediaTextRequest) (*FindMediaTextReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedMediaTextServiceServer) mustEmbedUnimplementedMediaTextServiceServer() {}

// UnsafeMediaTextServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaTextServiceServer will
// result in compilation errors.
type UnsafeMediaTextServiceServer interface {
	mustEmbedUnimplementedMediaTextServiceServer()
}

func RegisterMediaTextServiceServer(s grpc.ServiceRegistrar, srv MediaTextServiceServer) {
	s.RegisterService(&MediaTextService_ServiceDesc, srv)
}

func _MediaTextService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindMediaTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaTextServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MediaTextService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaTextServiceServer).Find(ctx, req.(*FindMediaTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MediaTextService_ServiceDesc is the grpc.ServiceDesc for MediaTextService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaTextService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MediaTextService",
	HandlerType: (*MediaTextServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Find",
			Handler:    _MediaTextService_Find_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
