{{- if .Values.external_service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.external_service.name }}
spec:
  type: ExternalName
  externalName: {{ .Values.external_service.external_name }}
  ports: 
    - port: {{ .Values.external_service.external_port }}
{{- end }}